### ISSUE TITLE
Module util is missed

### ISSUE THREAD

**Issue by thutzr** [georgehc/dksa#1]
Hi, 

I run `intervals_nks_reg_diag.py` and it imports util which is missed in the directory.  Here is the error I got. Could you provide this module, please?
```
Traceback (most recent call last):
  File "prediction_intervals/intervals_nks_res_diag.py", line 162, in <module>
    from util import compute_median_survival_time, compute_mean_survival_time
ModuleNotFoundError: No module named 'util'
```

**Comment by georgehc** [comment]
Thanks for pointing this out. I just uploaded the missing file (util.py).
